app = ""

[build]
  image = "teddysun/xray:latest"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 443
    handlers = ["tls"]

[experimental]
  cmd = ["xray", "-config=/etc/xray/config.json"]
